# book settings
title: Developmental Conservation
author: Maarten van der Sande, & Simon van Heeringen
logo: docs/imgs/logo.png

repository:
  url: https://github.com/vanheeringen-lab/DevelopmentalBiology
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: docs/imgs/logo.png


# execution
execute:
  execute_notebooks: force
  timeout: -1
