name: DevelopmentalRegulation

channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - matplotlib
  - pandas
  - scipy
  - jupyter
  - scikit-learn
  - gimmemotifs
  - pip
  - pip:
    - scikit-misc
    - jupyter-book
    - scikit-learn-extra
